# Site settings
#
# Custom variables are accessible in the templates via {{ site.myvariable }}.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Elysia Hwang, design developer
description: > # this means to ignore newlines until "baseurl:"
  Elysia is a designer and front-end developer in Atlanta.
baseurl: "/2016" # the subpath of your site, e.g. /blog
# url: "http://elysiahwang.com" # the base hostname & protocol for your site
twitter_username: elycheea
github_username:  elycheea

# Build settings
markdown: kramdown
theme: minima
port: 5000

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /work/:path/
